title: Elizabeth Gabli
subtitle: A Future Data Scientist
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: https://github.com/gablieli/gablieli.github.io
baseurl: "" 

# Navigation
urls:
    - text: Home
      url: /
    - text: About Me
      url: /about
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: gablieli.png
author: Elizabeth Gabli
author_bio: Hi, my name is Elizabeth Gabli.
author_email: "gablieli@msu.edu"
author_location: Michigan
author_website_url: "https://github.com/gablieli/gablieli.github.io"
typewrite-text: devlopr is a jekyll framework built for developers. You can edit this in _config.yml file
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Huron Valley State Bank 
              company_logo: HVSB.png
              company_url: https://www.hvsb.com/
              designation: Marketing Intern
              description: Supported the “Bank at School” program, developed flyers, facilitated with the Marketing Director small group meeting with students off-site, helped with elementary school marketing booths, and organized supplies.
              visibility: true
            - company_name: Huron Valley State Bank 
              company_logo: HVSB.png
              company_url: https://www.hvsb.com/
              designation: CSR
              description: Managed new and served existing clients with transactions in Checking, Savings, Money Market, Credit Card, Debit Cards, Safety deposit box, Vault cash accounting, night drop, inactive account client calls, and daily cash drawer responsibility for up to $75,000 dollars in cash counting. -Adapted to a diverse client base during a global pandemic. Keeping a professional atmosphere. -Trained new employees. Took the initiative to support new employees to improve workflow. Worked at the front counter and drive-thru banking in a fast-paced environment.  Being an active team player to grow synergy and workplace culture.
              visibility: true
            - company_name: Christina R Hamill CPA
              company_logo: 
              company_url: https://christinarhamillcpa.com/
              designation: Part-time Accounting Intern
              description: Prepared personal income tax 1040 returns through Intuit.  Supported CPA and accounting manager in the preparation of files for their review. Worked on clients' bookkeeping and payroll through QuickBooks. Recorded transactions from bank statements. Grew in a real-world business vocabulary environment. Clerical office duties.  Utilized Excel for calculations for hours, sales tax, and other accounting data calculations. Made copies, filed, shredded, organized files, and answered the phone. Supported a professional environment.
              visibility: true
            - company_name: Michigan State University Activities Board
              company_logo: UAB.png
              company_url: https://uabevents.com/
              designation: Events Coordinator                    
              description: Work independently to plan between 4-6 events a semester like live acts and novelty events. Plan large-scale events including a week of events at Homecoming and annual Funn at the Munn ice skating event.
              visibility: true



# Education
author_education_details:
              - college_logo: OCC.png
                college_name: Oakland Community College
                college_url: https://www.oaklandcc.edu/startyoursomeday/?gad_source=1&gclid=CjwKCAjwmrqzBhAoEiwAXVpgomld-DX9dVCQ1WBoCuZ2RZutp6NlMI89rrONYyBJyXNjem7YfYwiOBoCRGsQAvD_BwE&gclsrc=aw.ds
                college_degree: Business
                description: Associates Of Business from 2020-2022
                visibility: true
              - college_logo: MSU.png
                college_name: Michigan State University
                college_url: https://msu.edu/
                college_degree: Data Science
                description: College of Natural Science Bachelors in Data Science from 2023-2025
                visibility: true 

# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true


# social links
github_username:  gablieli
facebook_username: elizabeth_gabli
linkedin_username: Elizabeth Gabli
instagram_username: elizabeth_gabli

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty


# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
