title: Elizabeth Gabli
subtitle: A Future Data Scientist
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "https://gablieli.github.io"
baseurl: "" 

# Navigation
urls:
    - text: Home
      url: /
    - text: About Me
      url: /about/

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: gablieli.png
author: Elizabeth Gabli
author_bio: Hi, my name is Elizabeth Gabli.
author_email: "gablieli@msu.edu"
author_location: Michigan
author_website_url: "https://github.com/gablieli/gablieli.github.io"
typewrite-text: 
hero_cover_img: cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Huron Valley State Bank 
              company_logo: HVSB.png
              company_url: https://www.hvsb.com/
              designation: Marketing Intern
              description: I worked at Huron Valley State Bank from September 2019 to March 2020. Supported the “Bank at School” program, developed flyers, facilitated with the Marketing Director small group meeting with students off-site, helped with elementary school marketing booths, and organized supplies.
              visibility: true
            - company_name: Huron Valley State Bank 
              company_logo: HVSB.png
              company_url: https://www.hvsb.com/
              designation: Part-Time CSR
              description: I worked at Huron Valley State Bank from 2020 to 2021 as a CSR. I Managed new and served existing clients with transactions in Checking, Savings, Money Market, Credit Card, Debit Cards, Safety deposit box, Vault cash accounting, night drop, inactive account client calls, and daily cash drawer responsibility for up to $75,000 dollars in cash counting. -Adapted to a diverse client base during a global pandemic. Keeping a professional atmosphere. -Trained new employees. Took the initiative to support new employees to improve workflow. Worked at the front counter and drive-thru banking in a fast-paced environment.  Being an active team player to grow synergy and workplace culture.
              visibility: true
            - company_name: Christina R Hamill CPA
              company_logo: 
              company_url: https://christinarhamillcpa.com/
              designation: Part-Time Accounting Intern
              description: I started working at Christina Hamill CPA in 2022, and in August 2022, I transitioned to a seasonal intern role to accommodate my return to school. During my time there, I gained valuable experience in various aspects of accounting and office management. I prepared personal income tax 1040 returns using Intuit and supported both the CPA and the accounting manager by preparing files for their review. Additionally, I worked on clients' bookkeeping and payroll through QuickBooks, recording transactions from bank statements. This role allowed me to develop a strong business vocabulary and understand the practical applications of accounting principles. I handled clerical office duties, such as making copies, filing, shredding documents, organizing files, and answering phones, which helped maintain a professional environment. I also utilized Excel for various accounting calculations, including tracking hours, calculating sales tax, and other essential data tasks. Overall, my experience at Christina Hamill CPA provided me with a comprehensive understanding of the accounting field and improved my organizational and technical skills.
              visibility: true
            - company_name: Michigan State University Activities Board
              company_logo: UAB.png
              company_url: https://uabevents.com/
              designation: Events Coordinator                    
              description: In the fall of 2023, I began working for the University Activities Board (UAB), where I currently dedicate 20-25 hours a week. In this role, I work independently to plan and coordinate between 4-6 events each semester, including live performances and novelty activities. My responsibilities include organizing large-scale events, such as a week-long series of activities for Homecoming and the annual "Funn at the Munn" ice skating event. This position has significantly enhanced my skill set, particularly in time management, budgeting, effective communication via email, interpersonal interactions, and event planning. My experience with UAB has allowed me to develop strong organizational abilities and the capacity to manage multiple tasks efficiently while ensuring the success of each event.
              visibility: true



# Education
author_education_details:
              - college_logo: MHS.png
                college_name: Milford High School
                college_url:  https://www.hvs.org/o/milford
                college_degree: High School Deploma
                description: I attended Milford High School from 2016 to 2020, where I actively participated in both academic and extracurricular activities. As a member of the DECA program, a prominent business organization, I honed my skills in case study analysis, time management, and organization. This experience equipped me with practical knowledge in business operations and strategic planning. Additionally, my involvement in the tennis team exemplified my dedication to teamwork and time management. Through rigorous training and competitive play, I developed valuable interpersonal skills and learned the importance of perseverance and collaboration. Overall, my high school journey was characterized by a balanced commitment to academic excellence and personal growth through active participation in DECA and the tennis team.
                visibility: true
              - college_logo: OCC.png
                college_name: Oakland Community College
                college_url: https://www.oaklandcc.edu/startyoursomeday/?gad_source=1&gclid=CjwKCAjwmrqzBhAoEiwAXVpgomld-DX9dVCQ1WBoCuZ2RZutp6NlMI89rrONYyBJyXNjem7YfYwiOBoCRGsQAvD_BwE&gclsrc=aw.ds
                college_degree: Associates in Business Administration
                description: From 2020 to 2022, I attended Oakland Community College, where I pursued an Associate in Business Administration degree. During this time, I achieved a GPA of 3.67 and was named to the Dean’s List for four semesters. My coursework provided a solid foundation in business principles and practical skills essential for professional success.
                visibility: true
              - college_logo: MSU.png
                college_name: Michigan State University
                college_url: https://msu.edu/
                college_degree: Bachelors in Data Science 
                description: Since August 2022, I have been attending Michigan State University's College of Natural Science, pursuing a Bachelor of Data Science. During this time, I have taken multiple coding classes, learning languages such as R, Python, and C++. These courses have provided me with essential programming skills for my degree and future career. In addition to my academic pursuits, I have been actively involved in volunteering with the University Activities Board (UAB), dedicating approximately 10 hours per week from 2022 to 2023. Through my involvement with UAB, I gained valuable experience in event planning on campus, developed goal-setting skills, improved my time management abilities, and learned about budgeting.
                visibility: true 

# Projects
author_project_details:
              - project_thumbnail: 
                project_title: 
                project_description:
                project_url: 
                visibility: false
              - project_thumbnail: 
                project_title: 
                project_description:
                project_url: 
                visibility: false


# social links
github_username:  gablieli
facebook_username: elizabeth_gabli
linkedin_username: Elizabeth Gabli
instagram_username: elizabeth_gabli

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty


# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
